### PR TITLE
added react blog project

### PR DESCRIPTION
**Pull request by bobbyy16**

### CODE REVIEW

**Review by devvsakib — CHANGES_REQUESTED** [review]
It seems your project has another git repository. You can delete .git folder from your project folder.
image

**Comment by bobbyy16** [comment]
done @devvsakib

**Comment by devvsakib** [comment]
> done @devvsakib

maybe you forget to make pull request. there is no changes

**Review by devvsakib — APPROVED** [review]
awesome pr

**Comment by bobbyy16** [comment]
Thankyou @devvsakib

**Pull request merged**
