### PR TITLE
added JavaScript-Timer Project

### PR DESCRIPTION
**Pull request by theshrish46**

### CODE REVIEW

**Comment by theshrish46** [comment]
Hey could you please review and merge the Project into the repo

**Review by devvsakib — CHANGES_REQUESTED** [review]
Hi @theshrish46, thanks for contribution, but your project contains another repository link. please remove .git folder from your project folder
image

**Comment by theshrish46** [comment]
Is it ok now?

**Comment by devvsakib** [comment]
try again from beginning, delete everything and clone this repo again

**Pull request closed without merging**
