### PR TITLE
Added animation to blog cards using framer motion

### PR DESCRIPTION
**Pull request by bilalakhter**
done

### CODE REVIEW

**Review by devvsakib — APPROVED** [review]
@bilalakhter , Thanks for your contribution,

**Review by devvsakib — CHANGES_REQUESTED** [review]
Please add your details in contritbutors.json file

**Comment by bilalakhter** [comment]
done

**Review by devvsakib — CHANGES_REQUESTED** [review]
Your PR has conflict. Please resolve the conflict

**Comment by devvsakib** [comment]
You have to resolve this conflict, I can't resolve it
image

**Comment by bilalakhter** [comment]
sorry i cannot either 
Capture

**Comment by devvsakib** [comment]
Step to solve this issue:
1. Go to your forked repo, and Sync Code
2. Open project folder in terminal and run `git pull`
3. `git add .`
4. `git commit -m "commit"`
5. `git push`

**Pull request closed without merging**
