### PR TITLE
LandingPage added

### PR DESCRIPTION
**Pull request by MoazamAli45**
I have added  my React Landing Page.
You can check this on:
https://webmeproject.netlify.app/

### CODE REVIEW

**Comment by otnansirk** [comment]
if this is your first contributor don't forget to add your information in the contributor.json file 
[Docs](https://github.com/devvsakib/power-the-web/blob/main/docs/contributor-card.md)

**Comment by MoazamAli45** [comment]
Yes this is my first contribution and I have updated the contributor.json.

**Review by devvsakib — APPROVED** [review]
Thank you

**Comment by MoazamAli45** [comment]
> Thank you 

Your welcome

**Pull request merged**
