### PR TITLE
Added hover effect to the cards and button using framer motion.

### PR DESCRIPTION
**Pull request by karthiknadar1204**

### CODE REVIEW

**Review by devvsakib — CHANGES_REQUESTED** [review]
Hey @karthiknadar1204 ,
You may didn't pull the latest changes. We have changed blog page layout.

Card are not aligned
image

Hover issue
image

Height issue
image
image

Please pull all the latest changed first and make PR again

**Comment by karthiknadar1204** [comment]
Will do!!1

**Comment by karthiknadar1204** [comment]
Have aligned the cards,working on the button

**Comment by karthiknadar1204** [comment]
@devvsakib ,have fixed the height issue,have changed the hover of the cards and have adjusted the buttons,should i initiate a new pull request of merge into this one?

**Comment by devvsakib** [comment]
Please do not change card height width. We have already fixed all the issues. You have to pull the latest changes from this repository. Go to your forked repository, Click on Sync Fork for the latest changes, then open your terminal and run `git pull`

Then just add the animation that you added

**Comment by karthiknadar1204** [comment]
the "Read more" button animations are fine.
will adjust the images within the container perfectly and revert back tomorrow.
Any more vhanges needed @devvsakib

**Comment by karthiknadar1204** [comment]
@devvsakib ,i closed the pr by mistake while trying to sync the repo,could you please reassign it to me.will fix the thumbnail pic alignment and any other enhancement needed for the cards.

**Pull request closed without merging**
