### PR TITLE
Added Text Tune project

### PR DESCRIPTION
**Pull request by nelsonuprety1**
I have added my project called Text Tune which is a text formatting tool. The working link for the app can be found here : https://text-tune.netlify.app/ 

And i also have added my name under contributors list. 

Thank you

### CODE REVIEW

**Review by devvsakib — CHANGES_REQUESTED** [review]
Hi, thank you for your contribution. 

Love the project, but your project folder contain another github repository. Please remove .git folder from your project
image

**Comment by nelsonuprety1** [comment]
I have removed the .git file from the folder. Thank you

**Comment by otnansirk** [comment]
Don't forget to add your project url to your profile in the contributors.json 
read this [docs](https://github.com/devvsakib/power-the-web/blob/main/docs/contributor-card.md)

**Comment by nelsonuprety1** [comment]
Hi there Could you please check the pull request. Thank you

**Review by devvsakib — CHANGES_REQUESTED** [review]
You didn't remove the .git folder from your project.

image

**Pull request closed without merging**
